"""
Pre-IPO / private company watchlist.

Default seed data uses last publicly-announced funding rounds.
Secondary market prices (from Forge Global, EquityZen, Hiive, etc.)
are manually updated by the user via the API.
"""

DEFAULT_COMPANIES: list[dict] = [
    # ── AI Foundation Models ──────────────────────────────────────────────────
    {
        "name": "OpenAI",
        "sector": "AI Foundation Models",
        "stage": "Pre-IPO",
        "last_valuation_b": 157.0,
        "last_round_type": "Series C",
        "last_round_amount_m": 6600,
        "last_round_date": "2024-10",
        "notes": "ChatGPT / GPT-4o maker. Largest private AI company by valuation.",
        "forge_url": "https://forgeglobal.com/openai_stock/",
    },
    {
        "name": "Anthropic",
        "sector": "AI Foundation Models",
        "stage": "Pre-IPO",
        "last_valuation_b": 18.4,
        "last_round_type": "Strategic",
        "last_round_amount_m": 4000,
        "last_round_date": "2024-03",
        "notes": "Claude AI. Backed by Amazon ($4B) and Google ($2B).",
        "forge_url": "https://forgeglobal.com/anthropic_stock/",
    },
    {
        "name": "xAI",
        "sector": "AI Foundation Models",
        "stage": "Pre-IPO",
        "last_valuation_b": 50.0,
        "last_round_type": "Series B",
        "last_round_amount_m": 6000,
        "last_round_date": "2024-05",
        "notes": "Elon Musk's AI lab. Grok LLM, integrated with X platform.",
        "forge_url": None,
    },
    {
        "name": "Mistral AI",
        "sector": "AI Foundation Models",
        "stage": "Pre-IPO",
        "last_valuation_b": 6.0,
        "last_round_type": "Series B",
        "last_round_amount_m": 1000,
        "last_round_date": "2024-06",
        "notes": "European open-weight LLM leader. Mistral 7B, Mixtral, Le Chat.",
        "forge_url": None,
    },
    {
        "name": "Cohere",
        "sector": "AI Foundation Models",
        "stage": "Pre-IPO",
        "last_valuation_b": 5.0,
        "last_round_type": "Series D",
        "last_round_amount_m": 500,
        "last_round_date": "2024-07",
        "notes": "Enterprise LLMs. Strong in RAG and Command R models.",
        "forge_url": None,
    },
    # ── AI Infrastructure & Data ──────────────────────────────────────────────
    {
        "name": "Databricks",
        "sector": "AI Infrastructure",
        "stage": "Pre-IPO",
        "last_valuation_b": 62.0,
        "last_round_type": "Series J",
        "last_round_amount_m": 10000,
        "last_round_date": "2024-12",
        "notes": "Data + AI platform. Acquired MosaicML. Strong enterprise ARR.",
        "forge_url": "https://forgeglobal.com/databricks_stock/",
    },
    {
        "name": "Scale AI",
        "sector": "AI Infrastructure",
        "stage": "Pre-IPO",
        "last_valuation_b": 13.8,
        "last_round_type": "Series F",
        "last_round_amount_m": 1000,
        "last_round_date": "2024-05",
        "notes": "AI data labeling + evaluation. Key DoD and enterprise contracts.",
        "forge_url": "https://forgeglobal.com/scale-ai_stock/",
    },
    {
        "name": "Hugging Face",
        "sector": "AI Infrastructure",
        "stage": "Pre-IPO",
        "last_valuation_b": 4.5,
        "last_round_type": "Series D",
        "last_round_amount_m": 235,
        "last_round_date": "2023-08",
        "notes": "The GitHub of ML — 1M+ models and datasets hosted on the Hub.",
        "forge_url": None,
    },
    {
        "name": "Together AI",
        "sector": "AI Infrastructure",
        "stage": "Pre-IPO",
        "last_valuation_b": 1.25,
        "last_round_type": "Series A",
        "last_round_amount_m": 106,
        "last_round_date": "2024-03",
        "notes": "Open-source LLM inference cloud + fine-tuning platform.",
        "forge_url": None,
    },
    # ── AI Semiconductors / Compute ───────────────────────────────────────────
    {
        "name": "Cerebras Systems",
        "sector": "AI Semiconductors",
        "stage": "S-1 Filed",
        "last_valuation_b": 7.0,
        "last_round_type": "Series F",
        "last_round_amount_m": 250,
        "last_round_date": "2024-08",
        "notes": "Wafer-scale AI chips. S-1 filed Sept 2024. Major G42 contract.",
        "forge_url": None,
    },
    {
        "name": "Groq",
        "sector": "AI Semiconductors",
        "stage": "Pre-IPO",
        "last_valuation_b": 2.8,
        "last_round_type": "Series D",
        "last_round_amount_m": 640,
        "last_round_date": "2024-08",
        "notes": "LPU chip for ultra-fast LLM inference. Strong benchmarks vs GPU.",
        "forge_url": None,
    },
    # ── AI Applications ───────────────────────────────────────────────────────
    {
        "name": "Perplexity AI",
        "sector": "AI Applications",
        "stage": "Pre-IPO",
        "last_valuation_b": 9.0,
        "last_round_type": "Series D",
        "last_round_amount_m": 500,
        "last_round_date": "2024-11",
        "notes": "AI-powered search engine. Rapidly growing web traffic.",
        "forge_url": None,
    },
    {
        "name": "Anysphere (Cursor)",
        "sector": "AI Applications",
        "stage": "Pre-IPO",
        "last_valuation_b": 2.5,
        "last_round_type": "Series B",
        "last_round_amount_m": 105,
        "last_round_date": "2024-12",
        "notes": "AI code editor (Cursor). Fastest-growing dev tool in recent memory.",
        "forge_url": None,
    },
    {
        "name": "Harvey AI",
        "sector": "AI Applications",
        "stage": "Pre-IPO",
        "last_valuation_b": 3.0,
        "last_round_type": "Series D",
        "last_round_amount_m": 300,
        "last_round_date": "2024-12",
        "notes": "AI for legal work. Backed by top law firms and OpenAI Fund.",
        "forge_url": None,
    },
    {
        "name": "ElevenLabs",
        "sector": "AI Applications",
        "stage": "Pre-IPO",
        "last_valuation_b": 3.3,
        "last_round_type": "Series C",
        "last_round_amount_m": 180,
        "last_round_date": "2024-01",
        "notes": "AI voice synthesis and cloning. Large creator economy footprint.",
        "forge_url": None,
    },
    # ── Crypto / Web3 Infrastructure ──────────────────────────────────────────
    {
        "name": "Consensys",
        "sector": "Crypto Infrastructure",
        "stage": "Pre-IPO",
        "last_valuation_b": 7.0,
        "last_round_type": "Series D",
        "last_round_amount_m": 450,
        "last_round_date": "2022-03",
        "notes": "MetaMask wallet, Infura RPC, Linea L2. Core Ethereum infra.",
        "forge_url": None,
    },
    {
        "name": "Fireblocks",
        "sector": "Crypto Infrastructure",
        "stage": "Pre-IPO",
        "last_valuation_b": 8.0,
        "last_round_type": "Series E",
        "last_round_amount_m": 550,
        "last_round_date": "2022-01",
        "notes": "Institutional crypto custody and settlement network.",
        "forge_url": None,
    },
    {
        "name": "Chainalysis",
        "sector": "Crypto Infrastructure",
        "stage": "Pre-IPO",
        "last_valuation_b": 8.6,
        "last_round_type": "Series F",
        "last_round_amount_m": 170,
        "last_round_date": "2022-05",
        "notes": "Blockchain analytics for compliance. Used by US gov agencies.",
        "forge_url": None,
    },
]
