name: LapioBTC
options:
  bundleIdPrefix: com.lapio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15"

settings:
  base:
    SWIFT_VERSION: "5.10"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  LapioBTC:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LapioBTC
    info:
      path: LapioBTC/Info.plist
      properties:
        CFBundleName: LAPIO BTC
        CFBundleDisplayName: LAPIO BTC
        CFBundleIdentifier: com.lapio.btc
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSFaceIDUsageDescription: "Used to protect app access"
        UIBackgroundModes:
          - remote-notification
    entitlements:
      path: LapioBTC/LapioBTC.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lapio.btc
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""   # Fill in your Apple Developer Team ID
